export const ACTION_TYPES = {
  INITIATE: "INITIATE",
  PLAY: "PLAY",
  PAUSE: "PAUSE",
  REPLAY: "REPLAY",
  PREVIOUS: "PREVIOUS",
  FORWARD: "FORWARD",
  ADD_START_TIME: "ADD_START_TIME",
  ADD_PAUSE_TIME: "ADD_PAUSE_TIME",
  UPDATE_CURRENT_DURATION: "UPDATE_CURRENT_DURATION",
  TOGGLE_MUTE: "TOGGLE_MUTE",
  SET_LOADING: "SET_LOADING",
  SET_HIDE_CONTROLS: "SET_HIDE_CONTROLS",
};

export const MODES = {
  PLAY: "PLAY",
  PAUSE: "PAUSE",
  END: "END",
};

export const CONTROLS_PARENT_ELEMENT_CLASSNAME = 'hide-pause-controls'
